sudo: required
services:
  - docker

before_install:
  - docker build -t chbright/react-test -f ./client/Dockerfile.dev ./client/.

script:
  - docker run -e CI=true chbright/react-test npm run test

after_success:
  - docker build -t chbright/multi-client ./client
  - docker build -t chbright/multi-nginx ./nginx
  - docker build -t chbright/multi-server ./server
  - docker build -t chbright/multi-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those
  - docker push chbright/multi-client
  - docker push chbright/multi-nginx
  - docker push chbright/multi-server
  - docker push chbright/multi-worker
